version: 2
multi-ecosystem-groups:
  updates:
    schedule:
      interval: yearly
updates:
  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: updates

  - package-ecosystem: npm
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: updates
