<script setup lang="ts">
import { makeDraggable, type IDragEvent } from "@vue-dnd-kit/core";
import { onBeforeUnmount, ref, useTemplateRef } from "vue";
import { ShortcutLinkHint, type ShortcutMetadata } from "~/lib/types";

// Props
const {index, items, metadata, onDragCancel, onDragEnd, onDragStart, onEdit, onHover} =
  defineProps<{
    index: number;
    items: ShortcutMetadata[];
    metadata: ShortcutMetadata;
    onDragCancel: () => void;
    onDragEnd: () => void;
    onDragStart: () => void;
    onEdit: () => void;
    onHover: (event: IDragEvent) => void;
  }>();

// Refs
const parent = useTemplateRef<HTMLElement>("parent");
const dragged = ref(false);
let suppressClickTimer: ReturnType<typeof setTimeout> | undefined = undefined;

// Methods
/**
 * Mark the shortcut so its post-drag click does not open the link.
 */
const onShortcutDragStart = () => {
  dragged.value = true;
  onDragStart();
};

/**
 * Allow normal clicks again after the browser has dispatched the post-drag click.
 */
const clearDragState = () => {
  if (suppressClickTimer !== undefined) {
    clearTimeout(suppressClickTimer);
  }

  suppressClickTimer = setTimeout(() => {
    dragged.value = false;
    suppressClickTimer = undefined;
  }, 0);
};

/**
 * Finish a drag and preserve its click suppression until the current event completes.
 */
const onShortcutDragEnd = () => {
  onDragEnd();
  clearDragState();
};

/**
 * Cancel a drag without allowing its resulting click to open the link.
 */
const onShortcutDragCancel = () => {
  onDragCancel();
  clearDragState();
};

/**
 * Prevent navigation when the click was generated by a completed drag.
 * @param event The click event
 */
const onClick = (event: MouseEvent) => {
  if (dragged.value) {
    event.preventDefault();
    dragged.value = false;
  }
};

/**
 * Handle context menu event
 * @param event The context menu event
 */
const onContextMenu = (event: MouseEvent) => {
  event.preventDefault();
  onEdit();
};

// Composables
const {isDragging} = makeDraggable(
  parent,
  {
    activation: {
      delay: 0.4,
      distance: 4,
    },
    events: {
      onHover,
      onSelfDragCancel: onShortcutDragCancel,
      onSelfDragEnd: onShortcutDragEnd,
      onSelfDragStart: onShortcutDragStart,
    },
    groups: ["shortcuts"],
  },
  () => [index, items],
);

// Lifecycle hooks
onBeforeUnmount(() => {
  if (suppressClickTimer !== undefined) {
    clearTimeout(suppressClickTimer);
  }
});
</script>

<template>
  <div
    ref="parent"
    class="touch-none"
    :class="{
      'opacity-40': isDragging,
    }"
  >
    <a
      class="centered-col cursor-grab rounded-xl m-4 p-1 active:cursor-grabbing"
      :href="metadata.link"
      rel="noopener noreferrer"
      @click="onClick"
      @contextmenu="onContextMenu"
    >
      <img
        :alt="`${metadata.title} icon`"
        class="h-[14vh] w-[14vh] object-contain"
        :src="metadata.icon"
      />
      <h1 class="text-lg">{{ metadata.title }}</h1>
    </a>

    <link
      v-if="metadata.linkHint !== ShortcutLinkHint.NONE"
      :href="metadata.link"
      :rel="metadata.linkHint"
    />
  </div>
</template>
