# Continuous deployment

name: Continuous deployment

on:
  # Run when a new release is published
  release:
    types:
      - published

  # Run when manually triggered
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Build release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install
        env:
          NODE_ENV: production

      - name: Build
        run: npm run build
        env:
          VITE_PEXELS_API_KEY: ${{ secrets.VITE_PEXELS_API_KEY }}
          VITE_UNSPLASH_ACCESS_KEY: ${{ secrets.VITE_UNSPLASH_ACCESS_KEY }}

      - name: Pack extension for Chrome
        run: npm run pack:chrome

      - name: Pack extension for Firefox
        run: npm run pack:firefox
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}

      - name: Upload the packed Chrome extension
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: new-tab.zip
          asset_name: new-tab.zip
          tag: ${{ github.ref }}

      - name: Upload the XPI
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: new-tab.xpi
          asset_name: new-tab.xpi
          tag: ${{ github.ref }}