# Continuous deployment

name: Continuous deployment

on:
  # Run when a new release is published
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    name: Build release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install
        env:
          NODE_ENV: production

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install CRX3
        run: go install github.com/mediabuyerbot/go-crx3/crx3@v1.6.0

      - name: Build
        run: npm run build
        env:
          VITE_PEXELS_API_KEY: "${{ secrets.VITE_PEXELS_API_KEY }}"
          VITE_UNSPLASH_ACCESS_KEY: "${{ secrets.VITE_UNSPLASH_ACCESS_KEY }}"

      - name: Write the CRX signing key
        run: echo "${{ secrets.CRX_SIGNING_KEY }}" > new-tab.crx.pem

      - name: Pack extension for Chrome (CRX)
        run: npm run pack:chrome:crx

      - name: Destroy the CRX signing key
        if: always()
        run: rm -f new-tab.pem

      - name: Pack extension for Chrome (ZIP)
        run: npm run pack:chrome:zip

      - name: Pack extension for Firefox
        run: npm run pack:firefox
        env:
          WEB_EXT_API_KEY: "${{ secrets.WEB_EXT_API_KEY }}"
          WEB_EXT_API_SECRET: "${{ secrets.WEB_EXT_API_SECRET }}"

      - name: Upload the packed Chrome extension (CRX)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: new-tab.crx
          asset_name: new-tab.crx.disabled
          tag: "${{ github.event.release.tag_name }}"

      - name: Upload the packed Chrome extension (ZIP)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: new-tab.zip
          asset_name: new-tab.zip
          tag: "${{ github.event.release.tag_name }}"

      - name: Upload the XPI
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: new-tab.xpi
          asset_name: new-tab.xpi
          tag: "${{ github.event.release.tag_name }}"
